function org_BlokusGame(){var cb='',_=' top: -1000px;',zb='" for "gwt:onLoadErrorFn"',xb='" for "gwt:onPropertyErrorFn"',ib='");',Ab='#',Mb='&',cc='.cache.js',Cb='/',Ib='//',bc=':',rb='::',oc=':moduleBase',bb='<!doctype html>',db='<html><head><\/head><body><\/body><\/html>',ub='=',Bb='?',wb='Bad handler "',ab='CSS1Compat',gb='Chrome',fb='DOMContentLoaded',W='DUMMY',ac="GWT module 'org.BlokusGame' may need to be (re)compiled",nc='Ignoring non-whitelisted Dev Mode URL: ',Pb='Unexpected exception in locale detection, using default: ',Ob='_',mc='__gwtDevModeHook:org.BlokusGame',Nb='__gwt_Locale',Hb='base',Fb='baseUrl',R='begin',X='body',Q='bootstrap',Eb='clear.cache.gif',tb='content',Kb='en',jc='end',hb='eval("',lc='file:',Xb='gecko',Yb='gecko1_8',S='gwt.codesvr.org.BlokusGame=',T='gwt.codesvr=',ic='gwt/clean/clean.css',yb='gwt:onLoadErrorFn',vb='gwt:onPropertyErrorFn',sb='gwt:property',nb='head',gc='href',kc='http:',Ub='ie10',Wb='ie8',Vb='ie9',Y='iframe',Db='img',kb='javascript',Z='javascript:""',dc='link',hc='loadExternalRefs',Jb='locale',Lb='locale=',ob='meta',mb='moduleRequested',lb='moduleStartup',Tb='msie',pb='name',U='org.BlokusGame',_b='org.BlokusGame.devmode.js',Gb='org.BlokusGame.nocache.js',qb='org.BlokusGame::',$='position:absolute; width:0; height:0; border:none; left: -1000px;',ec='rel',Sb='safari',jb='script',$b='selectingPermutation',V='startup',fc='stylesheet',eb='undefined',Zb='unknown',Qb='user.agent',Rb='webkit';var p=window;var q=document;s(Q,R);function r(){var a=p.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function s(a,b){if(p.__gwtStatsEvent){p.__gwtStatsEvent({moduleName:U,sessionId:p.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
org_BlokusGame.__sendStats=s;org_BlokusGame.__moduleName=U;org_BlokusGame.__errFn=null;org_BlokusGame.__moduleBase=W;org_BlokusGame.__softPermutationId=0;org_BlokusGame.__computePropValue=null;org_BlokusGame.__getPropMap=null;org_BlokusGame.__gwtInstallCode=function(){};org_BlokusGame.__gwtStartLoadingFragment=function(){return null};var t=function(){return false};var u=function(){return null};__propertyErrorFunction=null;var v=p.__gwt_activeModules=p.__gwt_activeModules||{};v[U]={moduleName:U};var w;function A(){C();return w}
function B(){C();return w.getElementsByTagName(X)[0]}
function C(){if(w){return}var a=q.createElement(Y);a.src=Z;a.id=U;a.style.cssText=$+_;a.tabIndex=-1;q.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==ab?bb:cb;w.write(b+db);w.close()}
function D(k){function l(a){function b(){if(typeof q.readyState==eb){return typeof q.body!=eb&&q.body!=null}return /loaded|complete/.test(q.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(q.removeEventListener){q.removeEventListener(fb,d,false)}if(e){clearInterval(e)}}}
if(q.addEventListener){q.addEventListener(fb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=B();var f=A();var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(hb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(ib));g=f.createElement(jb);g.language=kb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(jb);g.language=kb;g.text=c[i];e.appendChild(g);d(e,g)}}}
org_BlokusGame.onScriptDownloaded=function(a){l(function(){m(a)})};s(lb,mb);var n=q.createElement(jb);n.src=k;q.getElementsByTagName(nb)[0].appendChild(n)}
org_BlokusGame.__startLoadingFragment=function(a){return H(a)};org_BlokusGame.__installRunAsyncCode=function(a){var b=B();var c=A().createElement(jb);c.language=kb;c.text=a;b.appendChild(c);b.removeChild(c)};function F(){var c={};var d;var e;var f=q.getElementsByTagName(ob);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(pb),k;if(j){j=j.replace(qb,cb);if(j.indexOf(rb)>=0){continue}if(j==sb){k=i.getAttribute(tb);if(k){var l,m=k.indexOf(ub);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=cb}c[j]=l}}else if(j==vb){k=i.getAttribute(tb);if(k){try{d=eval(k)}catch(a){alert(wb+k+xb)}}}else if(j==yb){k=i.getAttribute(tb);if(k){try{e=eval(k)}catch(a){alert(wb+k+zb)}}}}}u=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;org_BlokusGame.__errFn=e}
function G(){function e(a){var b=a.lastIndexOf(Ab);if(b==-1){b=a.length}var c=a.indexOf(Bb);if(c==-1){c=a.length}var d=a.lastIndexOf(Cb,Math.min(c,b));return d>=0?a.substring(0,d+1):cb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=q.createElement(Db);b.src=a+Eb;a=e(b.src)}return a}
function g(){var a=u(Fb);if(a!=null){return a}return cb}
function h(){var a=q.getElementsByTagName(jb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Gb)!=-1){return e(a[b].src)}}return cb}
function i(){var a=q.getElementsByTagName(Hb);if(a.length>0){return a[a.length-1].href}return cb}
function j(){var a=q.location;return a.href==a.protocol+Ib+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==cb){k=h()}if(k==cb){k=i()}if(k==cb&&j()){k=e(q.location.href)}k=f(k);return k}
function H(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return org_BlokusGame.__moduleBase+a}
function I(){var i=[];var j;var k=[];var l=[];function m(a){var b=l[a](),c=k[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
l[Jb]=function(){var b=null;var c=Kb;try{if(!b){var d=location.search;var e=d.indexOf(Lb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Mb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=u(Jb)}if(!b){b=p[Nb]}if(b){c=b}while(b&&!t(Jb,b)){var h=b.lastIndexOf(Ob);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Pb+a)}p[Nb]=c;return b||Kb};k[Jb]={'default':0,en:1,zh:2};l[Qb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Rb)!=-1}())return Sb;if(function(){return b.indexOf(Tb)!=-1&&q.documentMode>=10}())return Ub;if(function(){return b.indexOf(Tb)!=-1&&q.documentMode>=9}())return Vb;if(function(){return b.indexOf(Tb)!=-1&&q.documentMode>=8}())return Wb;if(function(){return b.indexOf(Xb)!=-1}())return Yb;return Zb};k[Qb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};t=function(a,b){return b in k[a]};org_BlokusGame.__getPropMap=function(){var a={};for(var b in k){if(k.hasOwnProperty(b)){a[b]=m(b)}}return a};org_BlokusGame.__computePropValue=m;p.__gwt_activeModules[U].bindings=org_BlokusGame.__getPropMap;s(Q,$b);if(r()){return H(_b)}var n;try{alert(ac);return;var o=n.indexOf(bc);if(o!=-1){j=parseInt(n.substring(o+1),10);n=n.substring(0,o)}}catch(a){}org_BlokusGame.__softPermutationId=j;return H(n+cc)}
function J(){if(!p.__gwt_stylesLoaded){p.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=q.createElement(dc);b.setAttribute(ec,fc);b.setAttribute(gc,H(a));q.getElementsByTagName(nb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
s(hc,R);c(ic);s(hc,jc)}
F();org_BlokusGame.__moduleBase=G();v[U].moduleBase=org_BlokusGame.__moduleBase;var K=I();if(p){var L=!!(p.location.protocol==kc||p.location.protocol==lc);p.__gwt_activeModules[U].canRedirect=L;if(L){var M=mc;var N=p.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(nc+N)}N=cb}if(N&&!p[M]){p[M]=true;p[M+oc]=G();var O=q.createElement(jb);O.src=N;var P=q.getElementsByTagName(nb)[0];P.insertBefore(O,P.firstElementChild||P.children[0]);return false}}}J();s(Q,jc);D(K);return true}
org_BlokusGame.succeeded=org_BlokusGame();